### PR TITLE
added icons library

### PR DESCRIPTION
**Pull request by TNFlexso**
added new library: icons

### CODE REVIEW

**Comment by Michadelic** [comment]
On another note: The functionality you are implementing could now also be done with this new API on the icon font: https://openui5nightly.hana.ondemand.com/#/api/sap.ui.core.IconPool/methods/sap.ui.core.IconPool.registerFont

You can speficy a map of iconName -> HexCode as configuration either in a file or as object.
Might make your coding also a lot easier.

**Comment by Michadelic** [comment]
Deploy folder has been removed with this change, you can safely remove it from your project or rebase to the current master
https://github.com/UI5Lab/UI5Lab-central/pull/49

**Comment by Michadelic** [comment]
Looks good now! Thanks for the changes

**Comment by TNFlexso** [comment]
Thanks Michael!

Sorry for the issues, it was my first github contribution to an open source project, and it took some figuring out :-). I will look into the registerFont API, but as far as I can tell it is only available in version 1.57.

Cheers
Thomas

**Pull request merged**
