### PR TITLE
Update index page with new information

### PR DESCRIPTION
**Pull request by AnnFr**
I created two Wiki entries on the master branch in the UI5Lab-central repository. I took Arnds texts for "how to add a new library" and "How to contribute your Custom Control Library to UI5lab?". The change on this pull request contains the removal of the "contribute" circle from the index page as both texts are now available on the Wiki page.

### CODE REVIEW

**Comment by vobujs** [comment]
who do you want this to merge in?

**Comment by Michadelic** [comment]
@vobujs the preview folder is automatically put at the root of the gh-pages branch by the travis job. When this pull is merged, the ui5lab.io domain will point to this new index page

**Comment by vobujs** [comment]
misunderstanding: i meant "who" as in "what person"...anyway, will do it now :)

**Comment by Michadelic** [comment]
i think this might be a solution, adding the following line to the travis script:

echo "ui5lab.io" > CNAME
http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/

**Pull request merged**
